### ISSUE TITLE
Error in javascript running monocular 

### ISSUE THREAD

**Issue by rodcloutier** [helm/monocular#250]
Running the latest pull from github in my kubernetes cluster I keep getting errors `Unexpected token < in JSON at position 0` in the browser console and a spinning wheel. 

```
vendor.ef3063430e06959a3905.bundle.js:727 EXCEPTION: Unexpected token < in JSON at position 0
t.handleError @ vendor.ef3063430e06959a3905.bundle.js:727
```

Running Chrome browser Version 57.0.2987.133
Monocular deployed in minikube 0.19.0 using helm `helm install --name monocular deployment/monocular`.

Service started with `minikube service monocular-monocular-ui`

The monocular-api pods are not reporting any errors.

**Comment by migmartri** [comment]
Hi, 

Currently, out of the box, Monocular only supports running alongside an Nginx Ingress controller. See the requisites section [here](https://github.com/helm/monocular/blob/master/docs/deployment.md). This means that in order to access to the Monocular app, you need to do it through the Nginx ingress controller exposed service instead of from the UI.

I believe that your issue is the same one experienced here https://github.com/helm/monocular/issues/234

 There is an issue w.r.t supporting the deployment of monocular without an ingress controller where you can find a workaround https://github.com/helm/monocular/issues/235

Thanks for reporting the issue,

Regards,
Miguel

**Comment by rodcloutier** [comment]
Tested and it works fine with the ingress. I will close the issue since it is properly documented.
